kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-sio-standard-2
  annotations:
      volume.beta.kubernetes.io/storage-class: sio-standard
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
