---
apiVersion: v1
kind: Secret
metadata:
  name: sio-secret
type: kubernetes.io/scaleio
data:
  username: <base enc user>
  password: <base enc user>

---
kind: StorageClass
apiVersion: storage.k8s.io/v1beta1
metadata:
 name: sio-standard
provisioner: kubernetes.io/scaleio
parameters:
 gateway: https://localhost:443/api
 system: scaleio
 protectionDomain: default
 secretRef: sio-secret
 fsType: xfs
