apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: k8s-fio
spec:
  serviceName: "fio"
  replicas: 1
  selector:
    matchLabels:
      app: fio
  template:
    metadata:
      labels:
        app: fio
    spec:
      containers:
      - name: k8s-fio
        image: clusterhq/fio-tool
        imagePullPolicy: Always
        command: ["fio", "/fio-data/job.fio]
        env:
          - name: JOBFILES
            value: /fio/job.fio
          - name: PLOTNAME
            valueFrom:
            fieldRef:
              fieldPath: metadata.name
        livenessProbe:
          httpGet:
            path: /
            port: 8000
          initialDelaySeconds: 3
          periodSeconds: 3
        ports:
        - containerPort: 8000
          protocol: TCP
        resources:
          limits:
            cpu: 16
            memory: 32G
          requests:
            cpu: 16
            memory: 32G
        volumeMounts:
        - name: k8s-fio-job
          mountPath: /fio/
        - name: k8s-fio-data
          mountPath: /fio-data/
    volumes:
      - name: k8s-fio-job
        configMap:
          name: k8s-fio-job
  volumeClaimTemplates:
  - metadata:
      name: Gold
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1024Gi
